# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  displayName: 'Code Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool: RPLocalPool
    steps:
    - task: Maven@3
      displayName: 'Maven - Build and Test'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        goals: 'package test jacoco:report'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish JaCoCo Results'
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(Build.ArtifactStagingDirectory)/site/jacoco/*.xml'
        reportDirectory: '$(Build.ArtifactStagingDirectory)/site/jacoco/'
    

    
    

    