# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  jobs:
  - job: Build_Job
    displayName: 'Build'
    pool: RPLocalPool
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m -Dmaven.test.skip=true'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        goals: 'package'
- stage: Test
  jobs:
  - job: Unit_Test
    displayName: 'Unit Testing'
    pool: RPLocalPool
    steps:
      - task : Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'test'
- stage: Code Coverage
  jobs:
  - job: Code
    displayName: 'Code Coverage'
    pool: RPLocalPool
    steps:
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target'
