# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  displayName: 'Code Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool: RPLocalPool
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        goals: 'package test jacoco:report'
  - job: CopyFiles
    displayName: 'Copy'
    pool: RPLocalPool
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  
